#946 Add `--url` option for `kal new` and `{url}` for format in command line
pimutils/khal pull request #965
Opened 2020-10-06 21:21 UTC by ephase

This is a fist attempt to add `URL=` in a VEVENT with khal. you can add it only in command line with `--url` option with `khal new`.

You can display URL with `{url}` in format (botn in khal and ikhal).

2020-12-03 22:18 UTC, ephase commented
I wonder if URL verification is a good idea because URL verification is tricky, with a big false positive risk.

2021-01-18 23:40 UTC, ephase commented
Rebase today and decide to not implement URL verification.

2021-01-19 08:40 UTC, WhyNotHugo commented on CHANGELOG.rst
> +<<<<<<< HEAD
Mismerge:

```suggestion
```

2021-01-19 09:17 UTC, ephase commented on CHANGELOG.rst
> +<<<<<<< HEAD
Sorry for the mistake, line removed

2021-03-09 23:46 UTC, d7415 requested changes
Sorry this has taken so long - I started then got busy and forgot about it. I've suggested a few minor changes to the text. The code looks ok and worked on my basic testing.

It's worth thinking whether there's a need for a test here.

2021-03-09 23:46 UTC, d7415 commented on CHANGELOG.rst
> +* NEW add url input for `khal` and `ikhal`
```suggestion
* NEW Add url input for `khal` and `ikhal`
```

2021-03-10 21:35 UTC, ephase commented
@d7415 No problem, I'm really busy too here and don't have time to participate as I want to... For test, you talk about write some pytest? Or test for user input in khal / ikhal?

2021-04-09 16:29 UTC, d7415 commented
I've added some tests (and a tweak so that setting the URL to `""` removes the field altogether) and pushed to feature/946 in this repo - GitHub doesn't want to let me push to yours. If you're happy with them and can merge them into your branch to update the PR I think we're good to go.

2021-04-25 22:42 UTC, d7415 commented
I'm guessing @ephase is still busy. If I don't hear anything by the end of the week I'll just merge feature/946 from pimutils/khal.

2021-04-26 23:50 UTC, ephase commented
hi @d7415, sorry for not giving news here, but I'm really busy at the moment. I reviewed change and all seems OK. So I merged it to my branch.

2021-04-27 13:57 UTC, d7415 commented
Thanks!

2021-04-27 13:58 UTC, merged